    ; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = teensy
framework = arduino
monitor_speed = 115200
build_flags =
    -DRIO_EIGEN_DONT_VECTORIZE
    -DRIO_EIGEN_DONT_ALIGN_STATICALLY
    -Ilib/mavlink
    -Isrc
    -O2
    -DSERIAL3_RX_BUFFER_SIZE=512
lib_deps =
    hideakitai/ArduinoEigen@^0.3.0

[env:teensy40]
extends = common
board = teensy40
build_flags =
    ${common.build_flags}
    -I.pio/libdeps/teensy40/ArduinoEigen/ArduinoEigen
    -DSD_BUILTIN=0

; [env:teensy41]
; extends = common
; board = teensy41
; build_flags =
;     ${common.build_flags}
;     -I.pio/libdeps/teensy41/ArduinoEigen/ArduinoEigen
;     -DSD_BUILTIN=1
